#generated by claude code

import json
from datetime import datetime


def parse_stream(stream_file="../stream.txt"):
 
    snapshot = {
        "timestamp": datetime.now().isoformat(),
        "logs": [],
        "metrics": [],
        "topology": [],
        "k8s_events": [],
        "pods": [],
        "nodes": [],
    }

    current_event = ""
    with open(stream_file, "r") as f:
        for line in f:
            line = line.rstrip("\n")

            if line.startswith("event: "):
                current_event = line[len("event: "):]
                continue

            if not line.startswith("data: "):
                continue

            data_raw = line[len("data: "):]
            try:
                data = json.loads(data_raw)
            except json.JSONDecodeError:
                continue  # Go skips unparseable data lines silently

            if current_event == "logs":
                for entry in data.get("entries", []):
                    snapshot["logs"].append({
                        "component": entry.get("service", ""),
                        "message": entry.get("message", ""),
                    })

            elif current_event == "metrics":
                for hm in data.get("hostMetrics", []):
                    snapshot["metrics"].append({
                        "entity": hm.get("node", ""),
                        "metric": "cpu_used_pct",
                        "value": hm.get("cpuUsedPct", 0.0),
                    })
                for cr in data.get("containerResources", []):
                    try:
                        rx = float(cr.get("netRxBytes", 0))
                    except (TypeError, ValueError):
                        rx = 0.0
                    snapshot["metrics"].append({
                        "entity": cr.get("container", ""),
                        "metric": "net_rx_bytes",
                        "value": rx,
                    })

            elif current_event == "events":
                for ev in data.get("events", []):
                    dest = ev.get("dstService", "")
                    if dest == "":
                        dest = "external"  # catch missing destinations
                    snapshot["topology"].append({
                        "source": ev.get("srcService", ""),
                        "dest": dest,
                        "protocol": ev.get("protocol", ""),
                        "metadata": {
                            "operation": ev.get("operation", ""),
                            "count": str(ev.get("count", 0)),
                        },
                    })

    return snapshot


if __name__ == "__main__":
    snap = parse_stream()
    print({k: (len(v) if isinstance(v, list) else v) for k, v in snap.items()})
